on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest code
      uses: actions/checkout@v4

    - name: Use node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
        username: ${{ secrets.GIT_CPANEL_REACT_USER }}
        password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
        protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
        local-dir: ./dist/

    - name: Send Telegram Notification on Success
      if: success()
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="✅ Deploy completed successfully for the project on branch 'main'!"
    
    - name: Send Telegram Notification on Failure
      if: failure()
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="❌ Deploy failed for the project on branch 'main'. Please check the logs."
